spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psg/beebulbal
    username: postgres
    password: beebulbal123!

  jpa:
    generate-ddl: true

  main:
    allow-circular-references: true

security:
  jwt:
    token:
      secret-key: bulbalApp
      expire-length: 14400000



#    docker
#    username: beebulbal
#    password: beebulbal123!
# /du
