spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.28.141.23:5432/sweatter
    username: beenavigator
    password: beenavigator123
  jpa:
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 386058975571-iq9eh4ftnae9fij25fqtnc4kkkif3j3c.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  main:
    allow-circular-references: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: atemirkanov89@gmail.com
    password: pqdleunusseixhtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
  thymeleaf:
    check-template-location: true

security:
  jwt:
    token:
      secret-key: bulbalApp
      expire-length: 14400000

server-config:
  upload-path: '/var/www/html1/img'
#server-config:
#  upload-path: C:\Users\atemirkanov\Desktop\bulbal



#/var/lib/docker/volumes/bulbal/_data
#'${user.dir}/uploads'


