spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /bulbal
  port: 8080
#  ssl:
#    key-store: classpath:aza.jks
#    key-store-type: JKS
#    key-store-password: 3edcVFR$

